version: '3'

services:
  mongo:
    image: mongo:4
    container_name: mongo_compose
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./leanote/mongodb_backup:/leanote/mongodb_backup
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  leanote:
    image: liwenguang/leanote:2.6.1
    container_name: leanote_app_compose
    restart: always
    ports:
      - 9000
    volumes:
      - ./leanote/data_upload:/usr/local/leanote/public/upload
    links:
      - mongo
    environment:
      - SITE_URL=localhost:9000
      - DB_USERNAME=root
      - DB_PASSWORD=mongopwd
  nginx:
    image: nginx:1.14.0-alpine
    container_name: nginx_compose
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5050:5050
      - 4040:4040
    links:
      - leanote
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.pid:/etc/nginx/nginx.pid
      - ./nginx/www:/etc/nginx/www
      - ./nginx/logs:/etc/nginx/logs
